<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Vordr.Application</RootNamespace>
        <AssemblyName>Vordr.Application</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire" />
        <PackageReference Include="MediatR"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="Battery\Commands\" />
      <Folder Include="CpuUsage\Commands\" />
      <Folder Include="RamUsage\Commands\" />
    </ItemGroup>
    
</Project>
