<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
    <PropertyGroup>
        <RootNamespace>Vordr.Client.Monitoring</RootNamespace>
        <AssemblyName>Vordr.Client.Monitoring</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.5-pre406"/>
        <PackageReference Include="Serilog" Version="4.2.1-dev-02352"/>
        <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.1"/>
        <PackageReference Include="System.Drawing.Common" Version="10.0.0-preview.3.25173.2"/>
        <PackageReference Include="System.Management" Version="10.0.0-preview.3.25171.5"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Vordr.Common\Vordr.Common.csproj" />
    </ItemGroup>

</Project>
